stages:
  - build
  - deploy
  - down

variables:
  DEPLOY_PATH: "/home/marco/gitlab-ws/calendar-autodeploy/frontend"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $PORT $HOST_NAME >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - 'ls -al'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG --no-cache .
    - docker push $IMAGE_TAG
    - docker rmi $IMAGE_TAG
  only:
    - master
    - dev

deploy-prod:
  stage: deploy
  script:
    - ssh $USER_NAME@$HOST_NAME -p $PORT "mkdir -p $DEPLOY_PATH"
    - scp -P $PORT -rp docker-compose-prod.yml $USER_NAME@$HOST_NAME:$DEPLOY_PATH
    - | 
      ssh $USER_NAME@$HOST_NAME -p $PORT "cd $DEPLOY_PATH && 
        docker-compose -f docker-compose-prod.yml up --build --force-recreate -d"
  environment:
    name: production
    url: https://calendar.marcostevanon.ovh
  when:
    manual
  only:
    - master

deploy-dev:
  stage: deploy
  script:
    - ssh $USER_NAME@$HOST_NAME -p $PORT "mkdir -p $DEPLOY_PATH"
    - scp -P $PORT -rp docker-compose-dev.yml $USER_NAME@$HOST_NAME:$DEPLOY_PATH
    - |
      ssh $USER_NAME@$HOST_NAME -p $PORT "cd $DEPLOY_PATH &&
        docker-compose -f docker-compose-dev.yml up --build --force-recreate -d"
  environment:
    name: development
    url: https://dev.calendar.marcostevanon.ovh
    on_stop: 
      down-dev
  only:
    - dev

down-dev:
  stage: down
  script:
    - |
      ssh $USER_NAME@$HOST_NAME -p $PORT "cd $DEPLOY_PATH &&
        docker-compose -f docker-compose-dev.yml down"
  environment:
    name: development
    action: stop
  when: manual
  only:
   - dev