# PRODUCTION
version: "3"

services:
 calendar.marcostevanon.ovh:
    container_name: "calendar.marcostevanon.ovh"
    image: registry.gitlab.com/calendar-app/frontend:master
    restart: always
    labels:
      - "traefik.frontend.rule=Host:calendar.marcostevanon.ovh"
      - "traefik.port=80"
      - "traefik.enable=true"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - traefik
      
networks:
  traefik:
    external: true